name: CI

on:
  push:
    branches:
      - main
  pull_request: ~

env:
  CACHE_VERSION: 4
  DEFAULT_PYTHON: "3.12"
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          [
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "3.11",
            "3.12",
            "3.13",
            "3.14",
            "3.15-dev",
          ]
        django-version: ["<3", "<4", "<5", "<6"]
        exclude:
          # Django 2.x does not support Python 3.10+
          - python-version: "3.10"
            django-version: "<3"
          - python-version: "3.11"
            django-version: "<3"
          - python-version: "3.12"
            django-version: "<3"
          - python-version: "3.13"
            django-version: "<3"
          - python-version: "3.14"
            django-version: "<3"
          - python-version: "3.15-dev"
            django-version: "<3"
          # Django 3.x does not support Python 3.11+
          - python-version: "3.11"
            django-version: "<4"
          - python-version: "3.12"
            django-version: "<4"
          - python-version: "3.13"
            django-version: "<4"
          - python-version: "3.14"
            django-version: "<4"
          - python-version: "3.15-dev"
            django-version: "<4"
          # Django 4.x does not support Python 3.6/3.7 or 3.13+
          - python-version: "3.6"
            django-version: "<5"
          - python-version: "3.7"
            django-version: "<5"
          - python-version: "3.13"
            django-version: "<5"
          - python-version: "3.14"
            django-version: "<5"
          - python-version: "3.15-dev"
            django-version: "<5"
          # Django 5.x requires Python 3.10+
          - python-version: "3.6"
            django-version: "<6"
          - python-version: "3.7"
            django-version: "<6"
          - python-version: "3.8"
            django-version: "<6"
          - python-version: "3.9"
            django-version: "<6"
    steps:
      - uses: actions/checkout@v6
      - name: Python-${{ matrix.python-version }}-django${{ matrix.django-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -yqq gettext
          pip3 install -e ".[dev]"
          pip3 install "django${{ matrix.django-version }}"
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python manage.py compilemessages
          coverage run --source=django_zxcvbn_password_validator ./manage.py test
          coverage html
          coveralls debug --service=github

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        django-version: ["<4", "<5", "<6"]
    steps:
      - uses: actions/checkout@v6
      - name: Python-${{ matrix.python-version }}-django${{ matrix.django-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -yqq gettext
          pip3 install -e ".[pylint]"
          pip3 install "django${{ matrix.django-version }}"
      - name: Lint
        run: |
          pre-commit run pylint --all-files
